### ISSUE TITLE
DTMF Decoding with older radios

### ISSUE THREAD

**Issue by DL4OCH** [g4klx/YSFClients#103]
Looking into the DTMF.cpp YSFGateway request exactly that sequence for decoding DTMF commands sent. As I am using an older radio (FT-991) the DTMF-commands are generated by an IC in the analogue part. So I can't create that pattern anyway.
Do we have the chance to create a "virtual Wires-X" room, to have to ability to connect to FCS. Otherwise older C4FM-radios are locked out.
Modern C4FM-radios are creating a "virtual DTMF" in DN-mode, older do it by the microphone.
Not a real issue, just a request for a solution.

Best,
 Wilm, DL4OCH

**Comment by g4klx** [comment]
My ancient FT-1D sends the correct DTMF! However I like the idea, and I'll look into it. There are too many FCS rooms to add all of them so it'll have to be a subset of them defined in the ini file.

**Comment by DL4OCH** [comment]
If we can cherry-pick the rooms we like (manual editing of an .ini file), it'll be a great solution!

**Comment by g4klx** [comment]
That's how it's implemented. It's in GitHub now, but not tested. Have a look at the ini file and you will see the new "Entries=" keyword in it, commented out.

**Comment by DL4OCH** [comment]
It works like a charm !
Great work in almost zero time !

Thanks Jonathan !

**Comment by DL4OCH** [comment]
Just a final thought, which is minor, but a nice to have:

Could you add a description to the Entries? For instance:

Entries=FCS00199:Echo, ...

May you put this in the feature-request at the low end ;)

Best,
 Wilm, DL4OCH

**Comment by g4klx** [comment]
Done! The format is now a little different. You may have many "Entry=" lines in the ini file. It was easier that way.

**Comment by DL4OCH** [comment]
Wow !

Thanks a lot! Great work!
