### ISSUE TITLE
ECHO on YSFREFLECTOR

### ISSUE THREAD

**Issue by VK3MCK** [g4klx/YSFClients#112]
I am having a major problem with my YSFREFLECTOR YSF40422.  I have reloaded it so many times I have lost count, including putting it on a old pc  with the same results, loaded onto new SD cards & new pi boards.  After a few hours my call sign appears for a second time in the Connected to YSFGateways and when I check the log it has PORT 1033 or 1034 beside it. I use Pi-star digital dashboard to connect with my FT-70.  When it's not showing the additional port it works fine, but only for approx 10hrs then it just appears.

Here is what it is display in the log.  the echo starts when this additional port (1034 or 1033) is appearing for some reason.
![log](https://user-images.githubusercontent.com/40345953/42313439-1b83983c-8086-11e8-8e40-76d47515af38.jpg)

**Comment by davidbeauchesne** [comment]
I am seeing this issue as well.

Was a cause and solution ever found?
