### ISSUE TITLE
Loglines are duplicated after running YSFreflector for some days

### ISSUE THREAD

**Issue by acfnews** [g4klx/YSFClients#116]
While looking in our YSFDashboard noticed that loglines are shown duplicated.
Our dashboard: [http://ysfreflector.pi1vbg.ampr.org/](url)
Further investigating the actual log lines created by YSFReflector, show that the lines are really printed twice, starting at 2018-08-30 15:51:06.250:

YSFReflector-2018-08-28.log:M: 2018-08-28 18:19:27.591 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-28.log:M: 2018-08-28 18:46:58.090 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-28.log:M: 2018-08-28 19:06:53.479 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-30.log:M: 2018-08-30 15:51:06.250 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-30.log:M: 2018-08-30 15:51:06.250 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-30.log:M: 2018-08-30 18:52:03.627 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-30.log:M: 2018-08-30 18:52:03.627 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-30.log:M: 2018-08-30 18:52:09.368 Received data from PD1ACF-RON to ALL        at PI1HGD
YSFReflector-2018-08-30.log:M: 2018-08-30 18:52:09.368 Received data from PD1ACF-RON to ALL        at PI1HGD

The same issue is also reported on another reflector: [http://c4fm.pa7lim.nl/](url)

I am not sure if I am able to find the issue, and fix it, just want to raise awareness and observer if other reflectors have the same behaviour...

Ron
PD1ACF

**Comment by pd1acf** [comment]
Also just noticed that de to this issue, the 'connected gateways' is also not displayed correctly in the Dashboard.

After a restart of the Reflector, the problem does not appear anymore.

**Comment by pd1acf** [comment]
It looks like the issue reappeared today in my logfiles, directly after the logrotation.

Yesterdays file ends with correct unique lines:
root@ysfreflector:/var/log/ysfreflector# tail -5 YSFReflector-2018-09-04.log
M: 2018-09-04 23:54:03.718     PI1HGD    : 83.85.108.198:42000 3/60
M: 2018-09-04 23:56:03.725 Currently linked repeaters/gateways:
M: 2018-09-04 23:56:03.725     PI1HGD    : 83.85.108.198:42000 3/60
M: 2018-09-04 23:58:03.732 Currently linked repeaters/gateways:
M: 2018-09-04 23:58:03.732     PI1HGD    : 83.85.108.198:42000 2/60

But the new logfiles, has every line duplicated:
root@ysfreflector:/var/log/ysfreflector# head YSFReflector-2018-09-05.log
M: 2018-09-05 00:00:03.744 Currently linked repeaters/gateways:
M: 2018-09-05 00:00:03.744 Currently linked repeaters/gateways:
M: 2018-09-05 00:00:03.744     PI1HGD    : 83.85.108.198:42000 2/60
M: 2018-09-05 00:00:03.744     PI1HGD    : 83.85.108.198:42000 2/60
M: 2018-09-05 00:02:03.756 Currently linked repeaters/gateways:
M: 2018-09-05 00:02:03.756 Currently linked repeaters/gateways:
M: 2018-09-05 00:02:03.757     PI1HGD    : 83.85.108.198:42000 2/60
M: 2018-09-05 00:02:03.757     PI1HGD    : 83.85.108.198:42000 2/60
M: 2018-09-05 00:04:03.767 Currently linked repeaters/gateways:
M: 2018-09-05 00:04:03.767 Currently linked repeaters/gateways:

**Comment by pd1acf** [comment]
Seems reproducable, each day after logfile rotation : 


pd1acf@ysfreflector:/var/log/ysfreflector$ tail YSFReflector-2018-09-05.log
M: 2018-09-05 23:51:50.037 Currently linked repeaters/gateways:
M: 2018-09-05 23:51:50.037     PI1HGD    : 83.85.108.198:42000 1/60
M: 2018-09-05 23:53:50.048 Currently linked repeaters/gateways:
M: 2018-09-05 23:53:50.048     PI1HGD    : 83.85.108.198:42000 1/60
M: 2018-09-05 23:55:50.059 Currently linked repeaters/gateways:
M: 2018-09-05 23:55:50.059     PI1HGD    : 83.85.108.198:42000 0/60
M: 2018-09-05 23:57:50.069 Currently linked repeaters/gateways:
M: 2018-09-05 23:57:50.069     PI1HGD    : 83.85.108.198:42000 0/60
M: 2018-09-05 23:59:50.083 Currently linked repeaters/gateways:
M: 2018-09-05 23:59:50.083     PI1HGD    : 83.85.108.198:42000 0/60
pd1acf@ysfreflector:/var/log/ysfreflector$ head YSFReflector-2018-09-06.log
M: 2018-09-06 00:01:50.094 Currently linked repeaters/gateways:
M: 2018-09-06 00:01:50.094 Currently linked repeaters/gateways:
M: 2018-09-06 00:01:50.094     PI1HGD    : 83.85.108.198:42000 0/60
M: 2018-09-06 00:01:50.094     PI1HGD    : 83.85.108.198:42000 0/60
M: 2018-09-06 00:03:50.099 Currently linked repeaters/gateways:
M: 2018-09-06 00:03:50.099 Currently linked repeaters/gateways:
M: 2018-09-06 00:03:50.099     PI1HGD    : 83.85.108.198:42000 0/60
M: 2018-09-06 00:03:50.099     PI1HGD    : 83.85.108.198:42000 0/60
M: 2018-09-06 00:05:50.114 Currently linked repeaters/gateways:
M: 2018-09-06 00:05:50.114 Currently linked repeaters/gateways:

**Comment by pd1acf** [comment]
There seems to be a relation between the issue, and running in daemon mode:
- when in daemon mode the problem is present,
- when running as root, the problem does not appear

**Comment by ChrisK9EQ** [comment]
For people who are having this problem, try making the following change:

In /etc/YSFReflector.ini change:

DisplayLevel=1
to
DisplayLevel=0

[Guesswork = 1] When the program runs as a service stdout has nowhere to go. It appears that after certain conditions are met, Linux funnels stdout to the log file resulting in duplicated lines. [Guesswork = 0]

Please report back on your results.

If this works, I suspect a clean solution would be to have YSFReflector automatically set DisplayLevel  = 0 if it detects it is running as a service.

**Comment by ChrisK9EQ** [comment]
Since there have been no further comments, I suggest that this issue can be closed.
