### ISSUE TITLE
Please revert a848ccb / #132

### ISSUE THREAD

**Issue by AndyTaylorTweet** [g4klx/YSFClients#137]
Please revert commit a848ccb this is my "Alternate Disconnect" patch, this has side-effects on some radios, the command appears to be "get news", and some radios call that after connecting (the FT 100 does).

This is the last commit on Jan 29th, the the PR #132 was called "Alternate Disconnect" and should come out cleanly since it was the only change in that patch, if not I can write a PR to remove it.

**Comment by juribeparada** [comment]
OK, I did the revert

**Comment by AndyTaylorTweet** [comment]
Thanks - closing the request.
