### ISSUE TITLE
Question about yaesu's WIRES-X active node list

### ISSUE THREAD

**Issue by iddq** [g4klx/YSFClients#156]
Hi Jonathan,

Is it possible to list our MMDVM based repeater at yaesu's site or not?

https://www.yaesu.com/jp/en/wires-x/id/active_node.php

We don't see our repeater there and I could not answer the question to local HAMs about this is a configuration problem or this is something that is not possible because we don't use the original HRI-200. Can you please help?

Thank you

**Comment by ChrisK9EQ** [comment]
You can also check active nodes on HamOperator.com. This is delivered as an XML file for your browser to interpret using XSL.

MMDVM does not use the WiRES-X network, so your node will not show up there. Use the appropriate FCS or YSF lists to see your node.

This issue can be closed.
73,
Chris, K9EQ

**Comment by iddq** [comment]
Thank you.
