### ISSUE TITLE
Gateway issues, wiresX problem

### ISSUE THREAD

**Issue by iw9grl** [g4klx/YSFClients#19]
Hi

after configuration of the YSFGateway it works very bad .
WiresX works some times, and when it works, if I try to list the YSFReflector list it doesn't work.
Moreover, the RX Level ( done for DMR and DSTAR )  is too high , I see in the log MMDVM RX overflow .......

73

**Comment by dg9vh** [comment]
@iw9grl Did you try to play with the mode-dependent level-adjustments in MMDVM.ini?

**Comment by jruys** [comment]
I too had odd behaviour when pulling the YSFReflector list: page 1 would load fine, and page 2 would hardly ever. Playing with the MMDVM TX levels seem to solve it, so doubt if it's code related. Will re-test when DVMega C4FM code releases.
