### ISSUE TITLE
Reconnect after DTMF disconnect not working

### ISSUE THREAD

**Issue by OE5PON** [g4klx/YSFClients#218]
void CYSFGateway::processDTMF(unsigned char* buffer, unsigned char dt)
{
...
	case WXS_DISCONNECT:
		if (m_linkType == LINK_YSF) {
			m_inactivityTimer.stop();   // change to start
		if (m_linkType == LINK_FCS) {
			m_inactivityTimer.stop();  //change to start
}

**Comment by g4klx** [comment]
Fixed. Thanks for spotting it.
