### ISSUE TITLE
Ysfreflector log ip issue

### ISSUE THREAD

**Issue by ve2tbu** [g4klx/YSFClients#236]
I rebuilt my reflector yesterday and everythink whas ok except for the log folder. I try to change from 1 or 2 for detail but no difference  other thing they show the callsign of the connected user but not the ip of the connection. Not a good thing to block the user making some trouble on the network.

**Comment by g4klx** [comment]
Good point. The IP and port display got lost in the IPv6 upgrade. I've now reinstated it, I hope it works as it uses completely new code.

**Comment by ve2tbu** [comment]
Ok now they show a ip adress but its the same for all. Other thing when i change the log display for a full detail if i put 1 or 2 they change nothing. Ijust have the info level value

**Comment by g4klx** [comment]
It's fixed now I think.
