### ISSUE TITLE
Linking the wrong YSF reflector

### ISSUE THREAD

**Issue by rphillips** [g4klx/YSFClients#240]
There is a [thread](https://forum.pistar.uk/viewtopic.php?f=3&t=3199) in the pi-star forums where pi-star is linking the wrong YSF reflector. There appears to be an issue when linking a YSF reflector with a leading zero. When I link a YSF room via the pi-star website or a Yaesu FT-3D to room 01037, pi-star shows the correct room linked, but the radio shows FCS22627.

**Comment by partsguymatt** [comment]
Now April 2020 and this is still an ongoing issue.

**Comment by ChrisK9EQ** [comment]
I believe this is intended behavior so it won't change until someone has a better idea. It permits access to FCS reflectors by repurposing some of the YSF number space. You should be able to access the YSF reflector by using the web interface. I think you'd be better off suggesting a solution. There should really be an option to select if YSF receives the entire number space or if it is shared with FCS.

I believe the way to proceed would be to implement a solution, test it on your own installation, then request the change via a pull request.

Chris, K9EQ
