### ISSUE TITLE
Please assign a YSF room number for XLXCAT

### ISSUE THREAD

**Issue by yo3cat** [g4klx/YSFClients#241]
Good morning,

Please assign a YSF room number for XLXCAT (xlxcat.dstar-yo.ro)

Thank you,
Catalin 
YO3CAT

**Comment by g4klx** [comment]
Just create your reflector and it will assign itself an id. It is automatic.

**Comment by dg9vh** [comment]
@yo3cat did you already register your reflector at https://register.ysfreflector.de/ ? Seems not.

73 de Kim
DG9VH

**Comment by dg9vh** [comment]
Seems the issue is not persistent anymore because of no reaction - @g4klx I think you can close it :-)
