### ISSUE TITLE
Log file showing same IP for all users.

### ISSUE THREAD

**Issue by w4dbg** [g4klx/YSFClients#248]
On US-America-Link the IP address for each user is the same for all.

I think this is the same that is listed here? https://github.com/g4klx/YSFClients/issues/236

Logs can be seen here: http://americalink.radiotechnology.xyz/ysfreflector/

Looking for ideas on how to fix this?

Thanks,
Doug
W4DBG

**Comment by dg9vh** [comment]
This issue comes up with adding IPV6-support to the reflector and still persists also in the actual release.

**Comment by ve2tbu** [comment]
anyboby know if this issue is supposed to be corrected ? i try it tonight and its the same issue that i mentionned in febuary

**Comment by g4klx** [comment]
Fixed now I think.
