### ISSUE TITLE
YSFReflector BlockList

### ISSUE THREAD

**Issue by r3pij** [g4klx/YSFClients#251]
Dashboard does not correctly display callsign blocking in ysfreflector
![SmartSelect_20210227-170237_Chrome](https://user-images.githubusercontent.com/79754522/109389678-6a0abb00-791e-11eb-8065-b73c1280316b.jpg)

**Comment by g4klx** [comment]
The dashboard is not a part of my code. Please find the dashboard maintainer and report it

Sent from Yahoo Mail for iPhone


On Saturday, February 27, 2021, 14:09, r3pij <notifications@github.com> wrote:




Dashboard does not correctly display callsign blocking in ysfreflector

**Comment by dg9vh** [comment]
Please open an issue on the corresponding github-repository with some
loglines producing this output.

73 Kim

**Comment by r3pij** [comment]
> Please open an issue on the corresponding github-repository with some loglines producing this output. 73 Kim

I opened an issue on your github-repository https://github.com/dg9vh/YSFReflector-Dashboard/issues/30
