### ISSUE TITLE
[DGIdGateway] problems with FCS-Servers

### ISSUE THREAD

**Issue by dg9vh** [g4klx/YSFClients#252]
When trying to link to fcs26285-room the system does look for IP-address of host fcs26285.xreflector.net that is not existing. There is only a fcs262.xreflector.net ... So please modify the hostname to be looked up by reducing the hostname to the first 5 characters...

It's working with the trick to add fcs26285.xreflector.net into the /etc/hosts :-) but this is a quick & dirty solution.

73
Kim

**Comment by g4klx** [comment]
Do a pull and give it a go, it should be happier now.

**Comment by dg9vh** [comment]
M: 2021-02-28 14:22:54.772 Opening YSF network connection
I: 2021-02-28 14:22:54.772 Opening UDP port on 4200
I: 2021-02-28 14:22:54.893 Loaded 1061 YSF reflectors
M: 2021-02-28 14:22:54.893 Opening IMRS network connection
I: 2021-02-28 14:22:54.894 Opening UDP port on 21110
M: 2021-02-28 14:22:54.894 Added YSF Gateway to DG-ID 0 (Static)
M: 2021-02-28 14:22:54.894 Opening YSF network connection
I: 2021-02-28 14:22:54.894 Opening UDP port on 42026
M: 2021-02-28 14:22:54.894      Linking at startup
M: 2021-02-28 14:22:54.895 Added Parrot to DG-ID 1
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.895 Opening UDP port on 42012
M: 2021-02-28 14:22:54.895 Added YSF2DMR to DG-ID 10
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.895 Opening UDP port on 42015
M: 2021-02-28 14:22:54.895 Added YSF2DMR to DG-ID 11
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.895 Opening UDP port on 42017
M: 2021-02-28 14:22:54.895 Added YSF2NXDN to DG-ID 20
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.895 Opening UDP port on 42019
M: 2021-02-28 14:22:54.895 Added YSF2P25 to DG-ID 30
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.895 Opening UDP port on 42021
M: 2021-02-28 14:22:54.895 Added YSF:DE-Germany to DG-ID 40 (Static)
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.895 Opening UDP port on 42140
M: 2021-02-28 14:22:54.895      Linking at startup
M: 2021-02-28 14:22:54.895 Added YSF:DE-RAMSES to DG-ID 41 (Static)
M: 2021-02-28 14:22:54.895 Opening YSF network connection
I: 2021-02-28 14:22:54.896 Opening UDP port on 42141
M: 2021-02-28 14:22:54.896      Linking at startup
M: 2021-02-28 14:22:54.896 Added YSF:DE-RAMSES-II to DG-ID 42 (Static)
M: 2021-02-28 14:22:54.896 Opening YSF network connection
I: 2021-02-28 14:22:54.896 Opening UDP port on 42142
M: 2021-02-28 14:22:54.896      Linking at startup
M: 2021-02-28 14:22:54.896 Added YSF:DE-RAMSES-III to DG-ID 43 (Static)
M: 2021-02-28 14:22:54.896 Opening YSF network connection
I: 2021-02-28 14:22:54.896 Opening UDP port on 42143
M: 2021-02-28 14:22:54.896      Linking at startup
M: 2021-02-28 14:22:54.896 Added YSF:DE-PEGASUS to DG-ID 44 (Static)
M: 2021-02-28 14:22:54.896 Opening YSF network connection
I: 2021-02-28 14:22:54.896 Opening UDP port on 42144
M: 2021-02-28 14:22:54.896      Linking at startup
M: 2021-02-28 14:22:54.896 Added YSF:DE-DL-Saar to DG-ID 45 (Static)
M: 2021-02-28 14:22:54.896 Opening YSF network connection
I: 2021-02-28 14:22:54.896 Opening UDP port on 42145
M: 2021-02-28 14:22:54.896      Linking at startup
M: 2021-02-28 14:22:54.963 Added FCS:FCS26285 to DG-ID 50 (Static)
M: 2021-02-28 14:22:54.963 Opening FCS network connection
I: 2021-02-28 14:22:54.963 Opening UDP port on 42200
M: 2021-02-28 14:22:54.963      Linking at startup
M: 2021-02-28 14:22:54.997 Added Parrot to DG-ID 99
M: 2021-02-28 14:22:54.997 Opening YSF network connection
I: 2021-02-28 14:22:54.997 Opening UDP port on 42013
M: 2021-02-28 14:22:54.997 Opened connection to the APRS Gateway
M: 2021-02-28 14:22:54.997 Starting DGIdGateway-20210228
M: 2021-02-28 14:22:54.997 Linked to DE-Germany
M: 2021-02-28 14:22:54.997 Linked to DE-RAMSES
M: 2021-02-28 14:22:54.997 Linked to DE-RAMSES-II
M: 2021-02-28 14:22:54.997 Linked to DE-RAMSES-III
M: 2021-02-28 14:22:54.997 Linked to DE-PEGASUS
M: 2021-02-28 14:22:54.997 Linked to DE-DL-Saar
M: 2021-02-28 14:22:54.997 Linked to FCS262-85
M: 2021-02-28 14:22:56.823 Link successful to MMDVM


Looks like working :-) I'll close this issue.

73 de Kim
DG9VH
