### ISSUE TITLE
Change name my ysfreflector 76217

### ISSUE THREAD

**Issue by jots76** [g4klx/YSFClients#264]
Hello Jonathan Naylor,
I want to change the reflector name (76217) from 
Name "ysf738phuket" Description "ysf738phuket" 
to 
Name "YSF-138-Phuket" Description "YSF-138-Phuket TH"
Please do it for me.
Thank you very much.
E23JWE

**Comment by jots76** [comment]
Sorry Text editor (72612) to (76217)

**Comment by W3KIT-910** [comment]
This got done in your YSFReflector.ini then go to the YSFReflector Rgistery and edit your reflector info.  There is a limit on how many characters you can have.  16 for name and 14 for description.

W3KIT
