### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ibjosh1985** [g4klx/YSFClients#269]
how do i get 

54635;US-SWLA337;SWLA Link;ysf.kc5jmj.com;42000;001;http://ysf.kc5jmj.com

added to the YSFHosts.txt

**Comment by dg9vh** [comment]
See https://github.com/g4klx/YSFClients/blob/master/YSFGateway/README.md

There you find the command to put into the crontab for regular updates...

**Comment by ibjosh1985** [comment]
not for me for all of the others in SWLA some of them are old guys its just easier to just have it added where its not a big headache of call's. my repeater is setup and fine but for others who are not that savy will have a harder time

**Comment by dg9vh** [comment]
This is also the way others could update the YSFHosts.txt on their repeaters/hotspots etc.

**Comment by ibjosh1985** [comment]
they wont figure it out those guys can barley work there hotspot like i said it's easier having it in the system most of the guys are in there 60's and 70's.

**Comment by dg9vh** [comment]
Then there is no way to recommend...

**Comment by ibjosh1985** [comment]
what do you mean

**Comment by dg9vh** [comment]
If it is to complicated to add one line to the crontab all other methods of adding a reflector would be much more complicated for those users.
