### ISSUE TITLE
YSF block

### ISSUE THREAD

**Issue by LiamLewis2011** [g4klx/YSFClients#287]
Is it possible to block certain callsigns from accessing the reflector for example those who cause trouble or use too much profanity ?

**Comment by w4dbg** [comment]
If you compile latest version and tell the YSFReflector.ini file where to find BlockList.txt all you have to do is list call signs in a blank txt file like this:

W1ABC
W2ABC

In the .ini you can adjust how often the BlockList.txt is polled/checked... It blocks transmissions not physical connections.

**Comment by LiamLewis2011** [comment]
Hey thanks for getting back to me I am really new to this so could you give me a dig out on how to do that 


Sent from Yahoo Mail for iPhone


On Thursday, March 10, 2022, 12:18 pm, w4dbg ***@***.***> wrote:




If you compile latest version and tell the YSFReflector.ini file where to find BlockList.txt all you have to do is list call signs in a blank txt file like this:

W1ABC
W2ABC

In the .ini you can adjust how often the BlockList.txt is polled/checked... It blocks transmissions not physical connections.
