### ISSUE TITLE
YSF reflector and YSF GATEWAY

### ISSUE THREAD

**Issue by kc9gqr** [g4klx/YSFClients#73]
IF I have a YSF reflector and a YSF Gateway software running  with no radio hoooked to it and i point a open spot to that reflector will it pass GPS/Callsign to aprs.fi?

**Comment by dg9vh** [comment]
@kc9gqr The APRS-Data is not forwarded by the YSFReflector - it is forwarded by the YSFGateway, so you do not need to have the YSFReflector installed. All you need is set a proper password for APRS-IS. You can get your password at: http://apps.magicbug.co.uk/passcode/index.php

**Comment by kc9gqr** [comment]
Thank you for the response..

1.  Could you fix my reflector  to  say  US IL  instead..   I was in a
hurry and miss typed it..  Thank you.. Bradley  Haney kc9gqr

2.  does that mean i can point my SHARK RF to just a YSF GATEWAY software
and that is it?  As my setup is as follows..

Shark RF (OPEN SPOT) pointed at my own YSF REFLECTOR/YSF GATEWAY

**Comment by dg9vh** [comment]
Just make correct config in YSFReflector.ini, it updates by polling-response.
Am 02.10.2016 18:02 schrieb kc9gqr <notifications@github.com>:Thank you for the response..

1.  Could you fix my reflector  to  say  US IL  instead..   I was in a
hurry and miss typed it..  Thank you.. Bradley  Haney kc9gqr

2.  does that mean i can point my SHARK RF to just a YSF GATEWAY software
and that is it?  As my setup is as follows..

Shark RF (OPEN SPOT) pointed at my own YSF REFLECTOR/YSF GATEWAY

**Comment by dg9vh** [comment]
About OpenSpot I don't know...
Am 02.10.2016 18:02 schrieb kc9gqr <notifications@github.com>:Thank you for the response..

1.  Could you fix my reflector  to  say  US IL  instead..   I was in a
hurry and miss typed it..  Thank you.. Bradley  Haney kc9gqr

2.  does that mean i can point my SHARK RF to just a YSF GATEWAY software
and that is it?  As my setup is as follows..

Shark RF (OPEN SPOT) pointed at my own YSF REFLECTOR/YSF GATEWAY
