### ISSUE TITLE
Warning during make of YSFGateway

### ISSUE THREAD

**Issue by iw9grl** [g4klx/YSFClients#77]
Attached a picture 

![capture](https://cloud.githubusercontent.com/assets/16877668/19380096/dbf7383e-91f5-11e6-9f5c-b5cbaa48b743.PNG)

thank you
73

**Comment by g4klx** [comment]
I've made the changes highlighted, it should be clean now.

**Comment by iw9grl** [comment]
It works now .
Thank you 
73
