### ISSUE TITLE
YSFGateway tail with partial ECHO voice

### ISSUE THREAD

**Issue by iw9grl** [g4klx/YSFClients#79]
Hi

using the YSF mode with MMDVM, connected to a YSFReflector,  after the release of my FT1xD PTT, there is a tail of some seconds with my echo voice .
Is this a bug ?

73

**Comment by g4klx** [comment]
No, it happens in all the modes to some extent. Nothing to worry about.

**Comment by iw9grl** [comment]
Thank you Jonathan, it happens only in Fusion no problem in DMR e Dstar, it is very annoying .....
