### ISSUE TITLE
YSF On Raspberry Pi.

### ISSUE THREAD

**Issue by VortexFL** [g4klx/YSFClients#81]
I am installing this to connect our openspots to YSF.

I am installing this on Raspberry PI3 running 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux.  I used the Jesse Lite and installed GIT from repository.  The make ran successfully.

I am getting this error message after copying the files.
root@PIIMAGE022717_JESSELITE:/usr/local/bin# ./YSFReflector.sh start
./YSFReflector.sh: line 27: ./YSFReflector: No such file or directory

Here is the link I followed - https://register.ysfreflector.de/installation

I had to chmod the file.
chmod 755 /usr/local/bin/YSFReflector.sh

I verified I copied the files
root@PIIMAGE022717_JESSELITE:/usr/local/bin# ls -l /etc/YSF*
-rw-r--r-- 1 root root 275 Feb 27 10:55 /etc/YSFReflector.ini
root@PIIMAGE022717_JESSELITE:/usr/local/bin# ls -l /usr/local/bin/YSF*
-rwxr-xr-x 1 root staff 1627 Feb 27 10:55 /usr/local/bin/YSFReflector.sh
root@PIIMAGE022717_JESSELITE:/usr/local/bin# ls -l /var/run/YSF*
-rw-r--r-- 1 root root 0 Feb 27 11:13 /var/run/YSFReflector.pid
root@PIIMAGE022717_JESSELITE:/usr/local/bin#

Thanks
Mike - K4MKH

**Comment by dg9vh** [comment]
@VortexFL Hi,
as you can see at the end of this howto, it is said that the BINARY is supposed to be located in /usr/local/bin - not the startup-script.

The scipt to be named "YSFReflector.sh" is located in /etc/init.d/

The binary named YSFReflector has to be copied to /usr/local/bin to be in this standard... that is the problem you where running into.
just copy the binary and not the script...

73 de Kim
DG9VH

**Comment by VortexFL** [comment]
It looks like it started.  I have never did a make before , just run
compiled programs.  I will keep working on this now.

Thanks.

root@PIIMAGE022717_JESSELITE:/usr/local/bin# ps -ef | grep YSF
mmdvm      899     1  0 12:17 ?        00:00:00 ./YSFReflector
/etc/YSFReflector.ini

**Comment by ravny** [comment]
Hi All,

I installed and seems to be working .... 

mmdvm    21735     1  0 08:25 ?        00:00:00 ./YSFReflector /etc/YSFReflector.ini
root     22177 20305  0 08:28 pts/2    00:00:00 grep YSF

But when I check netstat -tulpn why there is ip 0.0.0.0 ? why is not local IP address ?

udp        0      0 0.0.0.0:42000           0.0.0.0:*                           21735/YSFReflector

Also when check at https://register.ysfreflector.de/ I can see its offline and also no ID shown 

Thank you for help

**Comment by dg9vh** [comment]
0.0.0.0 is ok, because the YSFReflector binds on each network-device, so your ethernet-device also on localhost.

Are you sure you made port 42000 accessible from the internet and the IP-address is static or in the registry is a correct hostname given with dyndns-support?

What reflector is all about? Give me please the name.

**Comment by ravny** [comment]
Hi,

tnx for replay, port on the fw should be opened since I add to DMZ zone. I done registration and select default port 42000 and also in YSFReflector.ini I entered port 42000. If you can search for reflector under name Slovenia you will see. Here is my dashboard http://xlx511.ddns.net:46193/index.php  

Brgds and tnx 
S56IAR Matej

**Comment by ravny** [comment]
Print out iptables see bellow 

root@xlx511:/# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:42000

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by dg9vh** [comment]
I saw you made a false registration with wrong hostname. you added http:// before the hostname - the registration should only be with hostname. I corrected it. Now your reflector is online.

**Comment by ravny** [comment]
Thank you ! uff I didnt notice that I by mistake copy / paste also http://*** 

Once more tnx and have a nice day 73
Matej
S56IAR

**Comment by dg9vh** [comment]
So this issue can be closed :)

**Comment by ravny** [comment]
Yes this can be closed tnx

**Comment by xe1dvi** [comment]
Ive have most of it figured out, only missing the BINARY file that goes into /usr/local/bin
Which one is it???
Thanks

**Comment by dg9vh** [comment]
You have to compile it by make clean all and this produces a binary YSFGateway within the source directory.

73 de Kim

**Comment by xe1dvi** [comment]
You mean to copy the contents of all 3 folders (YSFReflector, YSFGateway, YSFParrot) on /usr/local/bin/ after  
Please be more specific.
When I command ./YSFReflector.sh start is seams like is running but is not.

Thanks.
