### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by darkstar2002** [g4klx/YSFClients#92]
The ysfreflector is not creating new log files after midnight.
it also stops logging on the old file at midnight.

**Comment by ravny** [comment]
I have same issue and when you restart service than new log file is created and starts logging again.

Brgds
Matej
S56IAR

**Comment by pmaholm** [comment]
I'm also experiencing the same issue on an implementation I'm working on. Has anyone figured our why this is happening? I did notice that the logs always cut off at midnight UTC and not local midnight.

KC9QHF

**Comment by ChrisK9EQ** [comment]
Suggest this issue be closed as it is solved. Current installation instructions are clear on providing write access to /var/log.
