### ISSUE TITLE
Wires X with DSQ enable

### ISSUE THREAD

**Issue by iw2gob** [g4klx/YSFClients#93]
I cannot view YSFReflector list in wires x mode when DSQ is enabled. I can enter WIRES X mode with my FT-2D, but the request for the ysfreflector list times out. If I disable DSQ in MMDVMHost, the YSFReflector list is ok.

**Comment by ChrisK9EQ** [comment]
When using YSFReflector turn off DSQ. DSQ is a WiRES-X/Fusion feature. It serves no use on hotspots

Suggest this issue be closed with no action.
